slug: :mikutter_niconico
depends:
  mikutter: 3.0.1
  plugin: 
  - gui
  - gtk
  - settings
  - openimg
version: '4.0'
author: shibafu528
name: mikutter_niconico
description: mikutter上でニコニコ動画の情報をキャッチ
